version: '3.8'
services:
  my-app:
    image: izik247/employee-records
    environment:
      - DB_SERVER=${DB_USER}
      - DB_NAME=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
    ports:
      - "8080:8080"
    container_name: employee-records-container
    depends_on:
       mysql:
          condition: service_healthy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - "3306:3306"
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin
      environment:
        - PMA_HOST:${PMA_HOST}
        - PMA_PORT:${PMA_PORT}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      container_name: phpmyadmin-container
      depends_on:
        - mysql
      ports:
        - "8083:80"
volumes:
  mysql-data:
    driver: local